### PR TITLE
Update ai_utils.py to use deepai.org

### PR DESCRIPTION
**Pull request by curiousartem**
The ai_utils function now uses deepai.org's API for computing the response. The DeepAI API is more reliable compared to the old API, chat-aim.vercel.app.

### CODE REVIEW

**Comment by mishalhossin** [comment]
@curiousartem make it a draft

**Comment by curiousartem** [comment]
mkay

**Review by quantumxx — COMMENTED** [review]
Current API is truly unreliable.

**Comment by Aryan2-1** [comment]
It's asking for api key

**Comment by Aryan2-1** [comment]
I mistakenly made it to run for every message that's why it got rate limited I think how do I fix that

**Comment by mishalhossin** [comment]
fine i have done it myself

**Pull request closed without merging**
